### ISSUE TITLE
Docs - front page

### ISSUE THREAD

**Issue by peeples** [MISTY-pipeline/spectacle#93]
Things to update on the first page of the docs (https://spectacle-py.readthedocs.io/en/latest/):

Possible to make the bit that shows in the tab be "Spectacle" instead of "Quick example" ?

Emission is mentioned--- should probably be removed as ~all the things are for absorption, not emission. Maybe later.

" # doctest: +IGNORE_OUTPUT" line looks out of place?

Before "Create the multi-component spectral model," mention, "All column densities are given in log cm^-2".

The "* u.Unit('erg / Angstrom / cm^2 / s')" is unnecessary and unphysical--- the continuum is at 1 precisely because it is dimensionless.

Molly Peeples should be added to copyright

**Comment by nmearl** [comment]
> Possible to make the bit that shows in the tab be "Spectacle" instead of "Quick example" ?

You mean change the section title for the example from "Quick Example" to "Spectacle"?
